on:
  push:
    branches:
      - "main"

env:
  RUST_BACKTRACE: full

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Publish to wasix-org
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Tools
        run: |
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io curl tar jq

      - name: Setup autobuild
        run: |
          ASSET_URL=$(curl -s -H "Authorization: token ${{ secrets.AUTOBUILD_TOKEN }}" https://api.github.com/repos/wasmerio/autobuild/releases/latest | jq '.assets[0].url')
          curl -L --output autobuild.tar.gz -H "Accept: application/octet-stream" -H "Authorization: token ${{ secrets.AUTOBUILD_TOKEN }}" $ASSET_URL
          tar -xzvf autobuild.tar.gz
          chmod +x autobuild

      # Publish to wasix.org
      - name: Publish
        run: ./autobuild build --wasmer-token ${{ secrets.WASMER_CIUSER_PROD_TOKEN }} --owner wasmer --not-depot --dont-deploy-in-docker-build .
